[build]
  command = ""
  publish = "public"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/process-form"
  to = "https://survey-prep-app.onrender.com/process-form"
  status = 200
  force = true

[[redirects]]
  from = "/preview-data"
  to = "https://survey-prep-app.onrender.com/preview-data"
  status = 200
  force = true

[[redirects]]
  from = "/view-details/*"
  to = "https://survey-prep-app.onrender.com/view-details/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/generate-report/*"
  to = "https://survey-prep-app.onrender.com/generate-report/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/download-*"
  to = "https://survey-prep-app.onrender.com/:splat"
  status = 200
  force = true
